### ISSUE TITLE
Dealing with BigStitcher

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#101]
Hi,

we have a lot of tiled images, and I played around with BigStitcher to put them together. this works really nicely. However, the xml file tat BS generates seems not to work in our BDV. Could you check what is the issue...? Is the ```<tile> ```not supported by default?

[dataset.xml.zip](https://github.com/bigdataviewer/bigdataviewer-playground/files/4370110/dataset.xml.zip)

```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_222 [64-bit]; Windows 10 10.0; 574MB of 98237MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.preibisch.mvrecon.fiji.spimdata.imgloaders.FileMapImgLoaderLOCI cannot be cast to bdv.ViewerImgLoader
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:309)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.preibisch.mvrecon.fiji.spimdata.imgloaders.FileMapImgLoaderLOCI cannot be cast to bdv.ViewerImgLoader
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:305)
	... 5 more
Caused by: java.lang.ClassCastException: net.preibisch.mvrecon.fiji.spimdata.imgloaders.FileMapImgLoaderLOCI cannot be cast to bdv.ViewerImgLoader
	at sc.fiji.bdvpg.sourceandconverter.SourceAndConverterUtils.createSourceAndConverters(SourceAndConverterUtils.java:138)
	at sc.fiji.bdvpg.scijava.services.BdvSourceAndConverterService.register(BdvSourceAndConverterService.java:145)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataImporterXML.apply(SpimDataImporterXML.java:41)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataImporterXML.get(SpimDataImporterXML.java:33)
	at sc.fiji.bdvpg.scijava.command.spimdata.MultipleSpimDataImporterCommand.run(MultipleSpimDataImporterCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
 ```

**Comment by martinschorb** [comment]
OK,

when I export to hdf5 (even though it is slow like hell https://github.com/PreibischLab/BigStitcher/issues/68 and destroys some of the tiles ) it loads. So it seems to be an issue with the tif reader.

Would there be some way to deal with these tiles as one source? In some cases that would be hundreds of tiles and showing all of them as individual sources will be very confusing.

**Comment by NicoKiaru** [comment]
Do you thing you can share a minimal buggy example or dataset ?

`Tile` should not be a problem. But I will try to put the `BigStitcher` and our update site together in a single Fiji and see if something weird is happening

**Comment by martinschorb** [comment]
https://github.com/PreibischLab/BigStitcher/issues/68#issuecomment-602688194

has the original xml that works with BigStitcher and the tifs.

**Comment by NicoKiaru** [comment]
Good! I think I understand the problem. The issue is that I assume that the loader can provide `Volatile` views of the source and hence can be casted as `bdv.ViewerImgLoader`, but that's not always the case.

Looking on it

**Comment by NicoKiaru** [comment]
Done and uploaded to the update site. Please reopen in case of issue.
Just be aware that it's not responsive to use this loader and there are options to make 'volatile' sources that we can discuss
