### ISSUE TITLE
New UI bug(s)

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#109]
Hi,

- load a bunch of xml/h5
- show sources
- projection mode: Average
- adjust contrast, adjust view
- open new UI (I like it!)
- click the source/group icon at the top

``` 
BdvHandlePostprocessor:BdvHandle found.
Exception in thread "PainterThread" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:652)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:511)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:486)
	at net.imglib2.ui.PainterThread.run(PainterThread.java:86)
```

**Comment by NicoKiaru** [comment]
Ok, found the issue!

https://github.com/bigdataviewer/bigdataviewer-playground/commit/8276f5abd95208eb69f41b00b98f3d59e5393366

I'll push to the update site with these two fix right now

**Comment by NicoKiaru** [comment]
Pushed
