### ISSUE TITLE
native BDV export broken

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#126]
Hi,

when I use the native BDV plugin and try "Export current Image as HDF5/XML", I run into:

```
java.lang.NoClassDefFoundError: bdv/export/WriteSequenceToHdf5$LoopbackHeuristic
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
	at org.scijava.command.CommandInfo.createInstance(CommandInfo.java:250)
	at org.scijava.command.CommandModule.instantiateCommand(CommandModule.java:251)
	at org.scijava.command.CommandModule.<init>(CommandModule.java:101)
	at org.scijava.command.CommandInfo.createModule(CommandInfo.java:328)
	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:170)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:209)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:200)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:185)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: bdv.export.WriteSequenceToHdf5$LoopbackHeuristic
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

Could it be that the Playground interferes with the core functionality here or is this a bug in the main BDV?

**Comment by NicoKiaru** [comment]
Same issue as this one:

https://forum.image.sc/t/bigstitcher-update-breaks-bdv-export/36176

I'm using dependencies which are not into FIJI yet. This will be solved in FIJI's new release. I don't know when. But since we are not officially release, no need to fix this right now. It will be 'fixed on its own'.

**Comment by martinschorb** [comment]
OK, Thanks!

I am playing around with Amira conversion and using BioFormats to go BDV-> Amira, looks good right now.
