### ISSUE TITLE
crash after set bindings

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#128]
Hi,

I tried to change some bindings and the window did not close when clicking OK.

Then I get massive amounts of these errors whenever the mouse moves inside the BDV window:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at bdv.viewer.ViewerPanel.drawOverlays(ViewerPanel.java:538)
	at net.imglib2.ui.InteractiveDisplayCanvasComponent.paintComponent(InteractiveDisplayCanvasComponent.java:272)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by NicoKiaru** [comment]
Did you manage to fix it ? Normally there's a yaml file at the root of fiji, deleting it should restore the defaults

Yeah sorry, I pushed it a bit too early in the update site I think

**Comment by martinschorb** [comment]
```bigdataviewer.properties```is what I found. Still ```OK```in the bindings has no effect and the window stays open.

**Comment by NicoKiaru** [comment]
There should be also by a `bdvkeyconfig.yaml`, but I'm not sure about the location

What you can try at the moment, is : make a `bdvkeyconfig.yaml` file from the text below:

```
---
- !mapping
  action: 2d drag translate
  contexts: [bdv2D]
  triggers: [button2, button3]
- !mapping
  action: 2d rotate left
  contexts: [bdv2D]
  triggers: [LEFT]
- !mapping
  action: 2d zoom in
  contexts: [bdv2D]
  triggers: [UP]
- !mapping
  action: 2d rotate right
  contexts: [bdv2D]
  triggers: [RIGHT]
- !mapping
  action: 2d zoom out
  contexts: [bdv2D]
  triggers: [DOWN]
- !mapping
  action: 2d drag rotate
  contexts: [bdv2D]
  triggers: [button1]
- !mapping
  action: 2d scroll zoom
  contexts: [bdv2D]
  triggers: [meta scroll, shift ctrl scroll]
- !mapping
  action: 2d rotate right slow
  contexts: [bdv2D]
  triggers: [ctrl RIGHT]
- !mapping
  action: 2d zoom out slow
  contexts: [bdv2D]
  triggers: [ctrl DOWN]
- !mapping
  action: 2d zoom out fast
  contexts: [bdv2D]
  triggers: [shift DOWN]
- !mapping
  action: 2d rotate right fast
  contexts: [bdv2D]
  triggers: [shift RIGHT]
- !mapping
  action: 2d scroll rotate slow
  contexts: [bdv2D]
  triggers: [ctrl scroll]
- !mapping
  action: 2d zoom in fast
  contexts: [bdv2D]
  triggers: [shift UP]
- !mapping
  action: 2d rotate left fast
  contexts: [bdv2D]
  triggers: [shift LEFT]
- !mapping
  action: 2d scroll translate
  contexts: [bdv2D]
  triggers: [not mapped]
- !mapping
  action: 2d rotate left slow
  contexts: [bdv2D]
  triggers: [ctrl LEFT]
- !mapping
  action: 2d scroll rotate fast
  contexts: [bdv2D]
  triggers: [shift scroll]
- !mapping
  action: 2d zoom in slow
  contexts: [bdv2D]
  triggers: [ctrl UP]
- !mapping
  action: 2d scroll rotate
  contexts: [bdv2D]
  triggers: [scroll]
- !mapping
  action: drag translate
  contexts: [bdv3D]
  triggers: [button2, button3]
- !mapping
  action: rotate left
  contexts: [bdv3D]
  triggers: [LEFT]
- !mapping
  action: zoom in
  contexts: [bdv3D]
  triggers: [UP]
- !mapping
  action: rotate right
  contexts: [bdv3D]
  triggers: [RIGHT]
- !mapping
  action: zoom out
  contexts: [bdv3D]
  triggers: [DOWN]
- !mapping
  action: forward z
  contexts: [bdv3D]
  triggers: [COMMA]
- !mapping
  action: backward z
  contexts: [bdv3D]
  triggers: [PERIOD]
- !mapping
  action: drag rotate fast
  contexts: [bdv3D]
  triggers: [shift button1]
- !mapping
  action: drag rotate
  contexts: [bdv3D]
  triggers: [button1]
- !mapping
  action: scroll zoom
  contexts: [bdv3D]
  triggers: [meta scroll, shift ctrl scroll]
- !mapping
  action: rotate right slow
  contexts: [bdv3D]
  triggers: [ctrl RIGHT]
- !mapping
  action: zoom out slow
  contexts: [bdv3D]
  triggers: [ctrl DOWN]
- !mapping
  action: backward z slow
  contexts: [bdv3D]
  triggers: [ctrl PERIOD]
- !mapping
  action: forward z slow
  contexts: [bdv3D]
  triggers: [ctrl COMMA]
- !mapping
  action: scroll browse z slow
  contexts: [bdv3D]
  triggers: [ctrl scroll]
- !mapping
  action: axis x
  contexts: [bdv3D]
  triggers: [X]
- !mapping
  action: axis y
  contexts: [bdv3D]
  triggers: [Y]
- !mapping
  action: axis z
  contexts: [bdv3D]
  triggers: [Z]
- !mapping
  action: rotate left slow
  contexts: [bdv3D]
  triggers: [ctrl LEFT]
- !mapping
  action: zoom in slow
  contexts: [bdv3D]
  triggers: [ctrl UP]
- !mapping
  action: scroll browse z
  contexts: [bdv3D]
  triggers: [scroll]
- !mapping
  action: drag rotate slow
  contexts: [bdv3D]
  triggers: [ctrl button1]
- !mapping
  action: forward z fast
  contexts: [bdv3D]
  triggers: [shift COMMA]
- !mapping
  action: backward z fast
  contexts: [bdv3D]
  triggers: [shift PERIOD]
- !mapping
  action: zoom out fast
  contexts: [bdv3D]
  triggers: [shift DOWN]
- !mapping
  action: rotate right fast
  contexts: [bdv3D]
  triggers: [shift RIGHT]
- !mapping
  action: zoom in fast
  contexts: [bdv3D]
  triggers: [shift UP]
- !mapping
  action: rotate left fast
  contexts: [bdv3D]
  triggers: [shift LEFT]
- !mapping
  action: scroll browse z fast
  contexts: [bdv3D]
  triggers: [shift scroll]
```

Put:
* this file at the same level as `bigdataviewer.properties` 
* create also a folder named `bdvpgsettings` at the same level. 
* In the newly created folder `bdvpgsettings`, copy again the yaml file.

**Comment by NicoKiaru** [comment]
Reverted for now
