### ISSUE TITLE
Edit mode delete sources

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#146]
HI,

I selected a few sources in edit mode and then did rightclick->Delete Sources

```
[ERROR] Module threw error
java.lang.NoSuchFieldError: list
	at bdv.util.PlaceHolderOverlayInfo.viewerStateChanged(PlaceHolderOverlayInfo.java:138)
	at bdv.viewer.BasicViewerState.lambda$notifyListeners$3(BasicViewerState.java:1650)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at bdv.viewer.BasicViewerState.notifyListeners(BasicViewerState.java:1650)
	at bdv.viewer.BasicViewerState.checkVisibilityChanged(BasicViewerState.java:1660)
	at bdv.viewer.BasicViewerState.removeSources(BasicViewerState.java:850)
	at bdv.viewer.SynchronizedViewerState.removeSources(SynchronizedViewerState.java:566)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.lambda$removeFromAllBdvs$5(SourceAndConverterBdvDisplayService.java:201)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.removeFromAllBdvs(SourceAndConverterBdvDisplayService.java:201)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.remove(SourceAndConverterService.java:210)
	at sc.fiji.bdvpg.scijava.command.source.SourcesRemoverCommand.run(SourcesRemoverCommand.java:23)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by NicoKiaru** [comment]
Yes it's because of this (now resolved) issue : https://github.com/bigdataviewer/bigdataviewer-vistools/issues/46#event-3643680066

I need to push again to the update site

**Comment by NicoKiaru** [comment]
So edit more broken for now...

**Comment by martinschorb** [comment]
when I then trty to close the BDV window:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchFieldError: list
	at bdv.util.PlaceHolderOverlayInfo.viewerStateChanged(PlaceHolderOverlayInfo.java:138)
	at bdv.viewer.BasicViewerState.lambda$notifyListeners$3(BasicViewerState.java:1650)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at bdv.viewer.BasicViewerState.notifyListeners(BasicViewerState.java:1650)
	at bdv.viewer.BasicViewerState.checkVisibilityChanged(BasicViewerState.java:1660)
	at bdv.viewer.BasicViewerState.clearSources(BasicViewerState.java:887)
	at bdv.viewer.SynchronizedViewerState.clearSources(SynchronizedViewerState.java:578)
	at bdv.viewer.state.ViewerState.kill(ViewerState.java:554)
	at bdv.viewer.ViewerPanel.stop(ViewerPanel.java:1157)
	at bdv.viewer.ViewerFrame$1.windowClosing(ViewerFrame.java:123)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by martinschorb** [comment]
OK, then I wait for the push...

**Comment by martinschorb** [comment]
n5 looks good now

**Comment by NicoKiaru** [comment]
I'll push in a minute

**Comment by NicoKiaru** [comment]
Ok,should work now, please repoen if necessary
