### ISSUE TITLE
BigStitcher broken

### ISSUE THREAD

**Issue by SebastienTs** [bigdataviewer/bigdataviewer-playground#151]
Hi guys,

Sound project but when I install this plugin it breaks BigStitcher with this error message:

Fetcher-0
Fetcher-0
[ERROR] Module threw error
java.lang.NoSuchMethodError: bdv.viewer.ViewerPanel.getDisplay()Lnet/imglib2/ui/InteractiveDisplayCanvasComponent;
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.BDVPopup.initTransform(BDVPopup.java:341)
	at net.preibisch.stitcher.gui.popup.BDVPopupStitching.createBDV(BDVPopupStitching.java:306)
	at net.preibisch.stitcher.gui.StitchingExplorerPanel.<init>(StitchingExplorerPanel.java:205)
	at net.preibisch.stitcher.gui.StitchingExplorer.<init>(StitchingExplorer.java:113)
	at net.preibisch.stitcher.plugin.BigStitcher.run(BigStitcher.java:80)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Could you have a look / fix it?

Cheers,
S.

**Comment by NicoKiaru** [comment]
Yep, unfortunately it cannot work with BigStitcher right now because this project uses a more recent version of `bigdataviewer-core`.

There are 2 draft PRs open for BigStitcher (https://github.com/PreibischLab/BigStitcher/pull/79) and multiview reconstruction (https://github.com/PreibischLab/multiview-reconstruction/pull/30) in order to get the same version of `bigdataviewer-core`.

FYI the reason to get the most recent version of bdv-core is that it enables faster viewing of many sources.

ping @StephanPreibisch and @hoerldavid

**Comment by SebastienTs** [comment]
Ok, good that you acknowledge it!
It took me a good while to understand that it broke BigStitcher, isn't it
possible to detect this conflict and throw a warning when installing your
plugin?

**Comment by NicoKiaru** [comment]
Right! Let's make this clear ;-)

I modified readme.md

**Comment by NicoKiaru** [comment]
For the release version, we'll be careful about compatibility, but for now, we just put an unstable state warning
