### ISSUE TITLE
2d empty source model: matrix is singular

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-playground#245]
If one wants to make an empty source with no thickness, we get this error:
```
java.lang.RuntimeException: Matrix is singular.
	at net.imglib2.realtransform.AffineTransform3D.invert(AffineTransform3D.java:361)
	at net.imglib2.realtransform.AffineTransform3D.scale(AffineTransform3D.java:698)
	at sc.fiji.bdvpg.sourceandconverter.importer.EmptySourceAndConverterCreator.<init>(EmptySourceAndConverterCreator.java:128)
	at sc.fiji.bdvpg.sourceandconverter.importer.EmptySourceAndConverterCreator.<init>(EmptySourceAndConverterCreator.java:102)
```

**Comment by NicoKiaru** [comment]
Well, the empty source has to have a thickness.
