### ISSUE TITLE
Fiji not starting

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#55]
@NicoKiaru 

I copied the jar to the Fiji/jars folder and tried to start Fiji but got this error:

```        at org.scijava.Context.inject(Context.java:474)
        at org.scijava.Context.inject(Context.java:386)
        at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:238)
        at org.scijava.ui.DefaultUIService.discoverUIs(DefaultUIService.java:503)
        at org.scijava.ui.DefaultUIService.getDefaultUI(DefaultUIService.java:193)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:140)
        at org.scijava.AbstractGateway.launch(AbstractGateway.java:104)
        at net.imagej.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Error while executing the main() method of class 'net.imagej.Main':
java.lang.NullPointerException
        at net.imagej.legacy.ui.LegacyUI.ij1Helper(LegacyUI.java:121)
        at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:132)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:157)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:142)
        at org.scijava.AbstractGateway.launch(AbstractGateway.java:104)
        at net.imagej.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
```

When I removed the jar Fiji started again.

Any idea?

**Comment by NicoKiaru** [comment]
SHould work with https://github.com/bigdataviewer/bigdataviewer-playground/commit/b2b8563acd5b9af765c38a10e86fdeb1739187bd

**Comment by NicoKiaru** [comment]
You can try the new master

**Comment by NicoKiaru** [comment]
Hmm maybe it's something else.

I'll investigate

**Comment by NicoKiaru** [comment]
The main cause was an error in the comamnd listing. I removed it and FIJI starts. But I know get this error:
```
[ERROR] Module threw error
java.lang.NoSuchMethodError: bdv.VolatileSpimSource.nonVolatile()Lbdv/SpimSource;
	at sc.fiji.bdvpg.sourceandconverter.SourceAndConverterUtils.createSourceAndConverters(SourceAndConverterUtils.java:143)
	at sc.fiji.bdvpg.scijava.services.BdvSourceAndConverterService.register(BdvSourceAndConverterService.java:153)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataImporterXML.apply(SpimDataImporterXML.java:41)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataImporterXML.get(SpimDataImporterXML.java:33)
	at sc.fiji.bdvpg.scijava.command.spimdata.MultipleSpimDataImporterCommand.run(MultipleSpimDataImporterCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
`VolatileSpimSource.nonVolatile()` is not found. I guess it's a missing dependency or a version issue.

**Comment by NicoKiaru** [comment]
Ah it's an issue of versioning...

See :
https://github.com/bigdataviewer/bigdataviewer-core/commit/75e082a6686e6d980215c1550394fc4bedf6d702

The SpimSource are not built like that anymore. We'll need to explicitely define the versions. Or maybe it's an update site which is causing the issue because of a newer version being declared as a dependency...

**Comment by tischi** [comment]
> We'll need to explicitly define the versions. 

This will only help us within IntelliJ but not within Fiji :-(

That means with your Fiji a different version of `bdv-core` seems to be shipped, right? 
I would not know how to find out where it comes from? Do you know?

Current Fiji is the same as what we use, i.e. `27.0.1`
https://github.com/fiji/fiji/blob/15f288f4af6a929c7b16ec4373b68be01d8b64f4/pom.xml#L8

**Comment by NicoKiaru** [comment]
I suspected an update site so I tried with a fresh FIJI and I still get the error.

Weird. I continue to investigate.

**Comment by NicoKiaru** [comment]
All works now with a fresh FIJI and a single jar added to the jars folder. For some reason I had to explicitely define `bigdataviewer-core` version to 7.0.0. But I don't really get why it was working before actually. What I don't get if that the pom scijava is always 27.0.1, but the versions of the containing jars keeps continuing to be updating.

Anyway, you can try and let me know. I'm closing but please reopens if that doesn't solve it.

**Comment by tischi** [comment]
Does that mean it would _not_ work with `bigdataviewer-core` version `7.0.1`?

**Comment by NicoKiaru** [comment]
No idea... If the API do not change it could be ok. You can change the pom and try ?

**Comment by tischi** [comment]
I will work on it today and try to make it work for both versions.
