### ISSUE TITLE
Synchronize Views

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#89]
Hi, 
I tested this functionality:
```
SourceAndConverterBdvDisplayService:Create locations display of sourceandconverter of LM_s1_a2_ch2
[DEBUG] windowWidth = 1207
[DEBUG] windowHeight = 913
[DEBUG] viewerPhysicalWidth = 5.356162199536782
[DEBUG] viewerPhysicalHeight = 4.0515129148111875
[DEBUG] viewerPhysicalVoxelSpacingX = 0.004437582601107525
[DEBUG] viewerPhysicalVoxelSpacingY = 0.004437582601107544
[DEBUG] windowWidth = 1207
[DEBUG] windowHeight = 913
[DEBUG] viewerPhysicalWidth = 5.356162199536782
[DEBUG] viewerPhysicalHeight = 4.0515129148111875
[DEBUG] viewerPhysicalVoxelSpacingX = 0.004437582601107525
[DEBUG] viewerPhysicalVoxelSpacingY = 0.004437582601107544
[DEBUG] windowWidth = 1207
[DEBUG] windowHeight = 913
[DEBUG] viewerPhysicalWidth = 5.356162199536782
[DEBUG] viewerPhysicalHeight = 4.0515129148111875
[DEBUG] viewerPhysicalVoxelSpacingX = 0.004437582601107525
[DEBUG] viewerPhysicalVoxelSpacingY = 0.004437582601107544
[DEBUG] windowWidth = 1207
[DEBUG] windowHeight = 913
[DEBUG] viewerPhysicalWidth = 5.356162199536782
[DEBUG] viewerPhysicalHeight = 4.0515129148111875
[DEBUG] viewerPhysicalVoxelSpacingX = 0.004437582601107525
[DEBUG] viewerPhysicalVoxelSpacingY = 0.004437582601107544
[DEBUG] windowWidth = 1207
[DEBUG] windowHeight = 913
[DEBUG] viewerPhysicalWidth = 5.356162199536782
[DEBUG] viewerPhysicalHeight = 4.0515129148111875
[DEBUG] viewerPhysicalVoxelSpacingX = 0.004437582601107525
[DEBUG] viewerPhysicalVoxelSpacingY = 0.004437582601107544
BigDataViewer: Viewer Transform: 3d-affine: (-53.08292690213936, 219.00659124099417, -1.3407671986748201E-14, 122154.7919616187, 219.00659124099437, 53.08292690213953, -1.9975382907886143E-14, -78434.6382939172, -1.9246304005428568E-14, -2.6463668007464272E-14, -225.34791797462367, -107.24025512071788)
BdvHandlePostprocessor:BdvHandle found.
SourceAndConverterBdvDisplayService:Create locations display of sourceandconverter of s2
[ERROR] Module threw exception
java.lang.NullPointerException
	at sc.fiji.bdvpg.bdv.navigate.ViewerTransformSyncStarter.getViewTransformForInitialSynchronization(ViewerTransformSyncStarter.java:124)
	at sc.fiji.bdvpg.bdv.navigate.ViewerTransformSyncStarter.run(ViewerTransformSyncStarter.java:62)
	at sc.fiji.bdvpg.scijava.command.bdv.ViewSynchronizerCommand.run(ViewSynchronizerCommand.java:40)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Do all the BDVs have to contain the excact same sources??

**Comment by NicoKiaru** [comment]
No no, I think you just need to click several bdv windows when you launch the command (but select at least 2), with the CTRL button.

You may think they were selected but they were not. I will have to add a warning when nothing is selected.

**Comment by NicoKiaru** [comment]
Warning message added in https://github.com/bigdataviewer/bigdataviewer-playground/commit/f497540b251c6b3cbff3ad298cdaf7c834d0ba90
