### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#98]
Hi,

I run into this when trying to update Fiji...

![bdvplaygrd](https://user-images.githubusercontent.com/35071867/76535733-9f9f6580-647b-11ea-93c1-21fb1f83dbf8.png)

**Comment by NicoKiaru** [comment]
You need to download imglib2-5.2.8 (https://maven.scijava.org/service/local/artifact/maven/redirect?r=central&g=net.imglib2&a=imglib2&v=5.8.0&e=jar) and put it in the jars folder of your fiji - it couldn't be updated to the update site...

**Comment by martinschorb** [comment]
Uuh,

now Fiji does not even start up anymore...
```
java.lang.NoClassDefFoundError: org/scijava/AbstractGateway                                                         
        at java.lang.ClassLoader.defineClass1(Native Method)                                                        
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)                                                  
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)                                  
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)                                             
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)                                               
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)                                                   
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)                                                   
        at java.security.AccessController.doPrivileged(Native Method)                                               
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:269)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.ClassNotFoundException: org.scijava.AbstractGateway
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more
Falling back to remote updater at http://update.imagej.net/bootstrap.js
java.lang.NoClassDefFoundError: org/scijava/script/AbstractScriptLanguage
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at javax.script.ScriptEngineManager.initEngines(ScriptEngineManager.java:122)
        at javax.script.ScriptEngineManager.init(ScriptEngineManager.java:84)
        at javax.script.ScriptEngineManager.<init>(ScriptEngineManager.java:61)
        at net.imagej.launcher.RemoteUpdater.runAsJavascript(RemoteUpdater.java:86)
        at net.imagej.launcher.RemoteUpdater.runRemote(RemoteUpdater.java:71)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:189)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.ClassNotFoundException: org.scijava.script.AbstractScriptLanguage
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by NicoKiaru** [comment]
Damned. I look right now. (also chek you removed the old imglib2 jar)

**Comment by NicoKiaru** [comment]
With a fresh fiji, if you add the new `imglib2-5.6.8` and remove the old `imglib2-5.6.3` it works.

Maybe you have some other update sites / dependencies which interfere ?

**Comment by martinschorb** [comment]
Confirmed

**Comment by martinschorb** [comment]
OK, so the update worked...then it crashes on startup.

what I did
- virgin Fiji fresh download  -> _runs_
- replace imglib2 as instructed  -> _runs_
- update without any additional update sites, keep local imglib2  -> _runs_
- add Bdv-Playground and update

-> crash on startup (restart after successful update)

```
[GC (Allocation Failure)  103296K->8401K(761280K), 0.0122242 secs]                                                  
[WARNING] 2 exceptions occurred during plugin discovery.                                                            
Error while executing the main() method of class 'net.imagej.Main':                                                 
java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:281)                                
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:232)                                       
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:195)                                       
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:167)                                      
        at org.scijava.Context.<init>(Context.java:281)                                                                
        at org.scijava.Context.<init>(Context.java:237)                                                                
        at org.scijava.Context.<init>(Context.java:177)                                                                
        at org.scijava.Context.<init>(Context.java:163)
        at net.imagej.ImageJ.<init>(ImageJ.java:77)
        at net.imagej.Main.main(Main.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterService
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:281)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:232)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:342)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:270)
        ... 16 more
Caused by: java.lang.NoClassDefFoundError: net/imglib2/EuclideanSpace
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.initialize(SourceAndConverterService.java:236)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:355)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:270)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: net.imglib2.EuclideanSpace
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 46 more
```

**Comment by NicoKiaru** [comment]
Arf. The heck. I'll ask the gitter crowd.

**Comment by martinschorb** [comment]
Any news?

The moment I include your update site, Fiji update dies :-(
So no happy testing atm...

**Comment by NicoKiaru** [comment]
Hi Martin, 

Sorry I have to finish two other projects that have the priority now. I don't know if I will have time tomorrow. Sounds surprising but the rhythm of work has not diminished yet.

**Comment by NicoKiaru** [comment]
I will completely reset the update site. Everything is so screwed up that I cannot revert what has been done. And the upload do not even work anymore. This means that you will have to re install FIJI.

**Comment by NicoKiaru** [comment]
@martinschorb you can retry to update - it should be working now. Maybe you will have to reset FIJI a few times to finish the update. Let us know

**Comment by martinschorb** [comment]
Looks really good!

Thanks!

**Comment by NicoKiaru** [comment]
Ouf!
